# Copyright (c) 2023 Qualcomm Technologies, Inc.

# All Rights Reserved.
log:
  dir: log/train/detection/efficientdet
  frequency:
    iteration: 10

checkpoint:
  init: ~
  mac: ~


train:
  optim:
    learning_rate: 0.0001
    learning_rate_g: 0.1
    momentum: 0.9
    weight_decay: 0.00004

  scheduler:
    method: MultiStepLR
    gamma: 0.1
    step_size: [4]

  num_epochs: 7
  clip_grad: 2.

loss:
  alpha: 100.
  beta: 10.

cuda_devices: all
local_rank: 0
